config/routes.rb
Diplom::Application.routes.draw do
  resources :prices

  resources :users, :schools, :school_groups, :disciplines

  resources :contracts do
  end
  
  resources :groups do
    post :save_data, :on => :member
    get  :generate,  :on => :member    
  end

  resources :courses do
    post :save_data, :on => :member
    get  :generate,  :on => :member    
  end
  
  resources :schoolkids do
    get  :search,              :on => :collection
    post :change_session_year, :on => :collection
    get  :create_contract,     :on => :member
  end

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup
  match 'register' => 'users#create', :as => :register
  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  root :to => "home#index"

end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
  default_scope order(:full_name)

  has_many :courses, :dependent => :destroy
  has_and_belongs_to_many :contracts

  validates :full_name, :presence => true, 
                        :uniqueness => true, 
                        :length => {:in=>3...50}
  
  validates :short_name, :presence => true,
                         :uniqueness => true, 
                         :length => {:in=>2...30}
end

app/controllers/disciplines_controller.rb
# -*- coding: utf-8 -*-
class DisciplinesController < ApplicationController
  before_filter :check_regular_user
  
  def index
    respond_to do |format|
      format.html {@disciplines = Discipline.page(params[:page])}
      format.json do
        @disciplines = Discipline.where("lower(full_name) LIKE lower(?)","%#{params[:q]}%").all
        render :json=>@disciplines.map(&:attributes)
      end
    end
  end

  def show
    @discipline = @dis = Discipline.includes(:courses).where('disciplines.id = ? AND courses.year = ?', params[:id], session[:choice_year].to_i).first
  end

  def new
    @discipline = Discipline.new
  end

  def edit
    @discipline = Discipline.find(params[:id])
  end

  def create
    @discipline = Discipline.new(params[:discipline])
    if @discipline.save
      redirect_to @discipline, :notice=>'Дисциплина добавлена.'
    else
      render :action => "new"
    end
  end

  def update
    @discipline = Discipline.find(params[:id])
    if @discipline.update_attributes(params[:discipline])
      redirect_to @discipline, :notice=>'Дисциплина удалена.'
    else
      render :action => "edit"
    end
  end

  def destroy
    @discipline = Discipline.find(params[:id])
    @discipline.destroy
    redirect_to disciplines_url, :notice=>"Дисциплина удалена."
  end
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/views/disciplines/_form.html.haml
=form_for @discipline,:html=>{:multipart=>true} do |f|
  -if @discipline.errors.any?
    .div.error
      %h2 При сохранении произошли ошибки
      %ul
        -@discipline.errors.full_messages.each do |msg|
          %li=msg

  .field
    = f.label :full_name
    %br
    = f.text_field :full_name
  .field
    = f.label :short_name
    %br
    = f.text_field :short_name
  .actions
    = f.submit 'Сохранить'

app/views/disciplines/edit.html.haml
%h1 Редактирование дисциплины
= render 'form'
= link_to 'Показать', @discipline
\|
= link_to 'Назад', disciplines_path

app/views/disciplines/index.html.haml
%h1 Список дисциплин
%table
  %thead
    %tr
      %th=Discipline.human_attribute_name('full_name')
      -unless @disciplines.blank?
        %th
        %th
  %tbody
    -@disciplines.each do |discipline|
      %tr
        %td= link_to discipline.full_name, discipline
        %td= link_to 'Редактировать', edit_discipline_path(discipline)
        %td= link_to 'Удалить', discipline, :confirm => 'Вы уверены?', :method => :delete

%br
=link_to "Добавить дисциплину", new_discipline_path

app/views/disciplines/new.html.haml
%h1 Новая дисциплина
=render 'form'
=link_to 'Назад', disciplines_path

app/views/disciplines/show.html.haml
%h1=@discipline.full_name
.film
  .col
    %dt=Discipline.human_attribute_name(:short_name)
    %dt=@discipline.short_name
  .clear

-unless @discipline.courses.blank?
  %h2 Курсы
  -i = 1
  %table
    %thead
      %tr
        %th №
        %th Продолжительность
    %tbody
      -@discipline.courses.each do |course|
        %tr
          %td=i
          %td= link_to course.duration, course
        -i += 1
%br
=link_to "К списку дисциплин", disciplines_path
\|
=link_to "Редактировать", edit_discipline_path(@discipline)
\|
=link_to "Удалить", @discipline,:confirm => "Вы уверены?", :method => :delete