config/routes.rb
Diplom::Application.routes.draw do
  resources :prices

  resources :users, :schools, :school_groups, :disciplines

  resources :contracts do
  end
  
  resources :groups do
    post :save_data, :on => :member
    get  :generate,  :on => :member    
  end

  resources :courses do
    post :save_data, :on => :member
    get  :generate,  :on => :member    
  end
  
  resources :schoolkids do
    get  :search,              :on => :collection
    post :change_session_year, :on => :collection
    get  :create_contract,     :on => :member
  end

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup
  match 'register' => 'users#create', :as => :register
  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  root :to => "home#index"

end

app/models/contract.rb
# -*- coding: utf-8 -*-
class Contract < ActiveRecord::Base
  default_scope order(:number)
  paginates_per 30

  belongs_to :schoolkid
  belongs_to :price1, :class_name => "Price", :foreign_key => "first_sum"
  belongs_to :price2, :class_name => "Price", :foreign_key => "second_sum"
  has_and_belongs_to_many :disciplines  

  before_save :change_dates  
  
  PERIOD = ["1 год.", "2 года.", "Ускоренник"]
  EDUCATION_TYPE = ["Инженерное", "Экономическое", "Юридическое"]
  TYPES = ["Дополнительное соглашение", "Основной"]
  
  validates :number,   :presence => true,
                       :uniqueness => true,
                       :length => {:in => 3...30}
  
  validates :first_sum,  :presence => true
  validates :second_sum, :presence => true
  
  validates :schoolkid_id,   :presence => true
  validates :education_type, :presence => true, :inclusion => {:in=>0...EDUCATION_TYPE.size}
  validates :ctype,          :presence => true, :inclusion => {:in=>0...TYPES.size}
  validates :period,         :presence => true, :inclusion => {:in=>0...PERIOD.size}
  validates :first_name,     :presence => true, :length => {:in => 2...40}
  validates :second_name,    :presence => true, :length => {:in => 2...40}
  validates :last_name,      :presence => true, :length => {:in => 2...40}

  validates :passport_date,   :presence => true
  validates :passport_number, :presence => true
  validates :passport_series, :presence => true
  validates :passport_place,  :presence => true, :length => {:in => 2...300}
  validates :city,            :presence => true, :length => {:in => 2...200}
  validates :address,         :presence => true, :length => {:in => 2...300}
  validates :telephone,       :presence => true, :format => /^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$/

  attr_reader :contract_discipline_ids, :schoolkid_tokens

  def russian_month(m)
    case m
    when 1 then m = " января "
    when 2 then m = " февраля "
    when 3 then m = " марта "
    when 4 then m = " апреля "
    when 5 then m = " мая "
    when 6 then m = " июня "
    when 7 then m = " июля "
    when 8 then m = " августа "
    when 9 then m = " сентября "
    when 10 then m = " октября "
    when 11 then m = " ноября "
    when 12 then m = " декабря "
    end 
    return m
  end

  def get_russian_date(date)
    "#{russian_month(date.month)} #{date.year}г."
  end
 
  def get_type?
    PERIOD[ctype]
  end

  def get_contract_type?
    TYPES[ctype]
  end

  def get_education_type?
    EDUCATION_TYPE[education_type]
  end

  def schoolkid_tokens=(id)
    self.schoolkid_id = id
  end

  def fio
    second_name + " " + first_name + " " + last_name
  end
  
  def contract_discipline_ids=(ids)
    self.discipline_ids = ids.split(',')
  end

  private
  
  def change_dates
    cur_date = Time.now
    self.signing_date = cur_date
    self.start_date = Time.mktime(cur_date.year, 9, 1)
    self.finish_date = Time.mktime(cur_date.year+1, 6, 31)
  end
end

app/controllers/contracts_controller.rb
# -*- coding: utf-8 -*-
class ContractsController < ApplicationController
  before_filter :check_regular_user
  
  def index
    @contracts = Contract.page(params[:page])
  end

  def show
    @contract = Contract.includes(:schoolkid, :disciplines, :price1, :price2).find(params[:id])
    @schoolkid = @contract.schoolkid
    respond_to do |format|    
      format.pdf { 
        if @contract.ctype == 1
          render 'main.pdf.erb'
        else
          @main_contract = Contract.where('schoolkid_id = ? AND ctype = 1', @schoolkid.id).first
          render 'addition.pdf.erb'
        end
      }
      format.html
    end
  end
  
  def new
    @contract = Contract.new
  end
  
  def edit
    @contract = Contract.includes(:disciplines).find(params[:id])
  end
  
  def create
    @contract = Contract.new(params[:contract])
    if @contract.save
      redirect_to @contract, :notice => 'Контракт добавлен.'
    else
      render :action => "new"
    end
  end
  
  def update
    @contract = Contract.find(params[:id])
    if @contract.update_attributes(params[:contract])
      redirect_to @contract, :notice => 'Контракт сохранен.'
    else
      render :action => "edit"
    end
  end

  def destroy
    @contract = Contract.find(params[:id])
    @contract.destroy
    redirect_to contracts_url, :notice => 'Контракт удален.'
  end
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/views/contracts/_form.html.haml
= form_for @contract do |f|
  -if @contract.errors.any?
    .div.error
      %h2= "При сохранении произошли ошибки"
      %ul
        - @contract.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :schoolkid_id
    %br
    =f.text_field :schoolkid_tokens,"data-pre"=> @contract.schoolkid.to_a.map(&:attributes).to_json
    = f.label :number
    %br
    = f.text_field :number, :size => 10
  .film
    .col  
      %b Ответственное лицо:
      .field 
        = f.label :second_name
        = f.text_field :second_name, :size => 20
        &nbsp;&nbsp;
        = f.label :first_name
        = f.text_field :first_name, :size => 15
        &nbsp;&nbsp;
        = f.label :last_name
        = f.text_field :last_name, :size => 20
      .field
        = f.label :passport_number
        %br
        = f.text_field :passport_number, :size => 10
        &nbsp;&nbsp;&nbsp;&nbsp;
        = f.label :passport_series
        = f.text_field :passport_series, :size => 10
      .field
        = f.label :passport_date
        %br
        = f.text_field :passport_date, :size => 10
        &nbsp;&nbsp;&nbsp;&nbsp;
        = f.label :passport_place
        = f.text_field :passport_place, :size => 20    
      .field
        = f.label :city
        %br
        = f.text_field :city, :size => 10
        &nbsp;&nbsp;&nbsp;&nbsp;
        = f.label :address
        = f.text_field :address, :size => 20
      .field     
        = f.label :telephone
        %br
        = f.text_field :telephone, :size => 10
      .clear
  .field
    =f.label :first_sum
    =f.select :first_sum, Price.all.map{|p| [p.value, p.id]}, :prompt => "0"
    %br
    #hide_field
      =f.label :second_sum
      =f.select :second_sum, Price.all.map{|p| [p.value, p.id]}, :prompt => "0"
  .field
    %b= f.label :ctype
    &nbsp;
    = f.radio_button :ctype, "1", :checked => @contract.ctype==1
    Основной договор
  .field
    %b= f.label :period
    &nbsp;
    = f.radio_button :period, "0", :checked => @contract.period==0, :class=>"period"
    1 год.
    &nbsp;
    = f.radio_button :period, "1", :checked => @contract.period==1, :class=>"period"
    &nbsp;
    2 года.
    = f.radio_button :period, "2", :checked => @contract.period==2, :class=>"period"
    &nbsp;
    Ускоренник
  .field
    %b= f.label :discipline_ids
    %br
    -for discipline in Discipline.find(:all)
      =check_box_tag :contract_discipline_ids, discipline.id, @contract.disciplines.include?(discipline)
      =discipline.full_name
      %br
  .actions
    = f.submit 'Сохранить'

app/views/contracts/addition.pdf.erb
\documentclass[10pt,a4paper]{amsart}
\usepackage{anysize}
\usepackage{multirow}
\usepackage[dvips]{graphics} 
\usepackage[utf8]{inputenc}
\usepackage[russian]{babel}
\usepackage[unicode]{hyperref}
\marginsize{20mm}{20mm}{20mm}{20mm}
\begin{document}

<% # Первая часть договора %>

\thispagestyle{empty}
\pagestyle{empty} 
{\bfseries Дополнительное соглашение к Договору \No} <%= @main_contract.number %> \phantom{aaaaaaaa} {\bfseries от } <<<%=@main_contract.signing_date.day%>>> <%=@main_contract.get_russian_date(@main_contract.signing_date)%>\\

об организации обучения слушателя {\bfseries <%= @schoolkid.fio %> } по дополнительным образовательным программам довузовской подготовки в ЧОУ ИМБ.

\begin{tabular}{p{13.0cm}p{3cm}}
г.Москва & <<<%=@contract.signing_date.day%>>> <%=@contract.get_russian_date(@contract.signing_date)%>\\
&\\
\end{tabular}

Мы, нижеподписавшиеся, от лица Частного образовательного учреждения высшего профессионального образования <<Институт менеджмента и бизнеса>> (ЧОУ ИМБ) ректор Авраамов Юрий Серафимович, с одной стороны и гражданин {\bfseries <%= @contract.fio %> } с другой стороны, заключили Дополнительное соглашение об установлении оплаты за обучение во втором семестре <%=@contract.start_date.year%>/<%=@contract.finish_date.year%> учебного года в размере <%= "#{@contract.price1.value} #{@contract.price1.russian_text}" %>  рублей 00 коп.}\\
Дополнительное соглашение является неотемлимой частью Договора.

\vskip 0.2cm
\begin{center}
{\bfseries Основные данные сторон}
\end{center}                         
\vskip 0.2cm
\begin{tabular}{p{8cm}p{0.5cm}p{8cm}}
{\bfseries  Гражданин} & & {\bfseries ЧОУ ИМБ}\\
<%= @contract.fio %>  & &  115280, Москва, Автозаводская ул., д.16\\
&&ИНН 7725066851, КПП 772501001 \\
Паспорт: серия <%= @contract.passport_series %> \No <%= @contract.passport_number %> & &  р/с  40703810038250101154,\\
Выдан <%= @contract.passport_place %>, <<<%=@contract.passport_date.day%>>> <%=@contract.get_russian_date(@contract.passport_date)%>  & &    в~Московском~банке~ОАО~<<Сбербанк~России>> г.Москвы  к/с~30101810400000000225 <<Сбербанк России ОАО>>\\
& & г.Москва  БИК 044525225  \\
&&\\
Домашний адрес: <%= @contract.city %>, <%= @contract.address %> & &    \\
&&  \\
Телефон: <%= @contract.telephone %> & &  \\
\rule[-2pt]{120pt}{0.4pt} (подпись)  & & Ректор  \rule[-2pt]{70pt}{0.4pt}  Авраамов Ю.С.\\
\end{tabular}
\vskip 1cm

<% # Вторая часть договора %>

\thispagestyle{empty}
\pagestyle{empty} 
{\bfseries Дополнительное соглашение к Договору \No} <%= @main_contract.number %> \phantom{aaaaaaaa} {\bfseries от } <<<%=@main_contract.signing_date.day%>>> <%=@main_contract.get_russian_date(@main_contract.signing_date)%>\\

об организации обучения слушателя {\bfseries <%= @schoolkid.fio %> } по дополнительным образовательным программам довузовской подготовки в ЧОУ ИМБ.

\begin{tabular}{p{13.0cm}p{3cm}}
г.Москва & <<<%=@contract.signing_date.day%>>> <%=@contract.get_russian_date(@contract.signing_date)%>\\
&\\
\end{tabular}

Мы, нижеподписавшиеся, от лица Частного образовательного учреждения высшего профессионального образования <<Институт менеджмента и бизнеса>> (ЧОУ ИМБ) ректор Авраамов Юрий Серафимович, с одной стороны и гражданин {\bfseries <%= @contract.fio %> } с другой стороны, заключили Дополнительное соглашение об установлении оплаты за обучение во втором семестре <%=@contract.start_date.year%>/<%=@contract.finish_date.year%> учебного года в размере <%= "#{@contract.price1.value} #{@contract.price1.russian_text}" %>  рублей 00 коп.}\\
Дополнительное соглашение является неотемлимой частью Договора.

\vskip 0.2cm
\begin{center}
{\bfseries Основные данные сторон}
\end{center}                         
\vskip 0.2cm
\begin{tabular}{p{8cm}p{0.5cm}p{8cm}}
{\bfseries  Гражданин} & & {\bfseries ЧОУ ИМБ}\\
<%= @contract.fio %>  & &  115280, Москва, Автозаводская ул., д.16\\
&&ИНН 7725066851, КПП 772501001 \\
Паспорт: серия <%= @contract.passport_series %> \No <%= @contract.passport_number %> & &  р/с  40703810038250101154,\\
Выдан <%= @contract.passport_place %>, <<<%=@contract.passport_date.day%>>> <%=@contract.get_russian_date(@contract.passport_date)%>  & &    в~Московском~банке~ОАО~<<Сбербанк~России>> г.Москвы  к/с~30101810400000000225 <<Сбербанк России ОАО>>\\
& & г.Москва  БИК 044525225  \\
&&\\
Домашний адрес: <%= @contract.city %>, <%= @contract.address %> & &    \\
&&  \\
Телефон: <%= @contract.telephone %> & &  \\
\rule[-2pt]{120pt}{0.4pt} (подпись)  & & Ректор  \rule[-2pt]{70pt}{0.4pt}  Авраамов Ю.С.\\
\end{tabular}
\vskip 1cm

\end{document}

app/views/contracts/edit.html.haml
%h1 Редактирование договора

= render 'form'
= link_to 'Показать', @contract
\|
= link_to 'Назад', contracts_path

app/views/contracts/index.html.haml
%h1 Список контрактов

%table
  %thead
    %tr
      %th=Contract.human_attribute_name('number')
      %th=Contract.human_attribute_name('signing_date')
      - unless @contracts.blank?
        %th
        %th
  %tbody
    - @contracts.each do |contract|
      %tr
        %td= link_to contract.number, contract
        %td= link_to contract.signing_date.strftime("%d.%m.%Y"), contract
        %td= link_to 'Редактировать', edit_contract_path(contract)
        %td= link_to 'Удалить', contract, :confirm => 'Вы уверены?', :method => :delete

=paginate @contracts
%br
= link_to 'Новый контракт', new_contract_path

app/views/contracts/main.pdf.erb
\documentclass[9pt,a4paper]{amsart}
\usepackage{anysize}
\usepackage{multirow}
\usepackage[dvips]{graphics} 
\usepackage[utf8]{inputenc}
\usepackage[russian]{babel}
\usepackage[unicode]{hyperref}
\marginsize{10mm}{10mm}{0mm}{5mm}

\begin{document}

\thispagestyle{empty}
\pagestyle{empty} 

\vskip -1cm
\begin{center}
 {\bfseries Д о г о в о р \No~<%= @contract.number %>}\\
{\bfseries об организации дополнительных образовательных услуг по довузовской подготовке}
\end{center}

\begin{tabular}{p{15.0cm}p{3cm}}
г.Москва & <<<%=@contract.signing_date.day%>>> <%=@contract.get_russian_date(@contract.signing_date)%>\\
&\\
\end{tabular}

Частное образовательное учреждение высшего профессионального образования <<Институт менеджмента и бизнеса>> именуемое в дальнейшем {\bfseries <<Институт>>}, в лице ректора Авраамова Юрия Серафимовича, действующего на основании Устава и лицензиии Рособрнадзора  \No 0710 от 24.02.2011 г., с одной стороны и Гражданин {\em <%= @contract.fio %>} с другой стороны заключили настоящий Договор о следующем:
\vskip -0.3cm
\begin{center}
{\bfseries 1. Предмет Договора }
\end{center}
\vskip -0.1cm

Настоящий Договор заключен между договаривающимися сторонами на обучение {\bfseries Слушателя} {\em <%= @schoolkid.fio %>} по дополнительным образовательным программам довузовской подготовки в целях дальнейшего его поступления в федеральное государственное бюджетное образовательное учреждение высшего профессионального образования <<Московский государственный индустриальный университет>> (ФГБОУ ВПО <<МГИУ>>), именуемое в дальнейшем {\bfseries <<МГИУ>>} на основании Договора \No .002/ДС2010 <<О сотрудничестве в сфере высшего образовани>> от 25 мая 2010г. между МГИУ и Институтом.

\vskip -0.3cm
\begin{center}
{\bfseries 2. Обязательства сторон }
\end{center}
\vskip -0.1cm

2.1. {\bfseries Гражданин} обязуется:

2.1.1. В десятидневный срок со дня заключения настоящего Договора произвести оплату обучение Слушателя за первый семестр обучения в размере {\em <%= "#{@contract.price1.value.to_s} (#{@contract.price1.russian_text})" %> рублей}.

2.1.2. Оплатить в десятидневный срок с момента начала занятий обучение Слушателя во втором и последующих (в случае двухгодичного цикла обучения) семестрах в соответствии с Дополнительным соглашением, подписанным обеими Сторонами и являющимся неотъемлемой частью настоящего Договора.

2.2. {\bfseries Слушатель} обязуется:

2.2.1. Регулярно посещать занятия довузовской подготовки, в полном объеме выполнять учебную программу, Устав и правила внутреннего распорядка Института и МГИУ.

2.2.2. В случае порчи имущества Института и МГИУ компенсировать материальный ущерб.

2.3. {\bfseries Институт} обязуется:

2.3.1. Проводить занятия со Слушателем по образовательным программам довузовской подготовки по предметам вступительных
испытаний в МГИУ: {\em <%= @contract.disciplines.map(&:full_name).join(', ') %>}.

2.3.2. Проводить ежемесячно рубежные контроли знаний, а по окончании каждого семестра итоговую аттестацию Слушателя по каждому изучаемому предмету.

2.3.3. Выдать по окончании полного цикла обучения и успешного прохождения итоговой аттестации по программам довузовской подготовки свидетельство установленного образца.
 
\vskip -0.3cm
\begin{center}
{\bfseries 3. Сроки и порядок действия Договора}
\end{center}
\vskip -0.1cm

3.1. Настоящий Договор заключен в двух экземплярах и вступает в действие со дня подписания его сторонами. Один экземпляр Договора хранится в Институте, второй у Гражданина.

3.2. Договор заключается на весь период обучения c <<<%=@contract.start_date.day%>>> <%=@contract.get_russian_date(@contract.start_date)%> по <<<%=@contract.finish_date.day%>>> <%=@contract.get_russian_date(@contract.finish_date)%>

3.3. Дополнительная образовательная услуга по программам довузовской подготовки в течение учебного года осуществляется по семестрам: первый семестр -  с момента начала занятий по декабрь; второй семестр - с января до завершения итоговой аттестации.

3.3. Дополнительная образовательная услуга по программам довузовской подготовки в течение учебного года осуществляется по семестрам: первый семестр, третий семестр -  с момента начала занятий по декабрь; второй семестр, четвертый семестр - с января до завершения итоговой аттестации.

3.3. Дополнительная образовательная услуга по программам довузовской подготовки  осуществляется  с января до завершения итоговой аттестации.

3.4. Настоящий Договор может быть расторгнут Гражданином в любой момент его действия, а Институтом в случае не выполнения Гражданином п.п. 2.1.1, 2.1.2 или Слушателем п. 2.2.1 настоящего Договора.

3.5. При досрочном расторжении Договора Гражданину возвращаются денежные средства, внесенные им за обучение, за вычетом затрат за уже предоставленную часть образовательной услуги.

3.6. После оплаты стоимость предоставляемой дополнительной образовательной услуги в текущем семестре не изменяется.
\vskip -0.3cm
\begin{center}
{\bfseries 4. Адреса, реквизиты и подписи Сторон}
\end{center}                         
\vskip -0.1cm
\begin{tabular}{p{7cm}p{0.5cm}p{9cm}}
{\bfseries 4.1. Гражданин} & & {\bfseries 4.2 Институт}\\
 <%= @contract.fio %>  & &  Частное~образовательное~учреждение~высшего~профессионального~образования~<<Институт~менеджмента~и~бизнеса>>\\
&&115280, Москва, Автозаводская ул., д.16\\
Паспорт: серия <%= @contract.passport_series %> \No <%= @contract.passport_number %> & &  ИНН 7725066851, КПП 772501001 \\
Выдан <%= @contract.passport_place %>, <<<%=@contract.passport_date.day%>>> <%=@contract.get_russian_date(@contract.passport_date)%> & &  р/с  40703810038250101154,  в~Московском~банке~ОАО~<<Сбербанк~России>> г.Москвы  к/с~30101810400000000225 ОАО <<Сбербанк России>>\\
& & г.Москва  БИК 044525225  \\
&&\\
Домашний адрес: <%= @contract.city %>, <%= @contract.address %> & &   Согласовано: \\
&&Ректор \rule[-2pt]{100pt}{0.4pt}   Авраамов Ю.С.\\
Телефон: <%= @contract.telephone %> & & Согласовано: \\
\rule[-2pt]{120pt}{0.4pt} (подпись)  & & Ректор ФГБОУ ВПО <<МГИУ>> \rule[-2pt]{40pt}{0.4pt}  Кошкин В.И.\\
\end{tabular}
\vskip 0.4cm
{\small С Уставом и Правилами внутреннего распорядка МГИУ и Института и с полным перечнем персональных данных, подлежащих обработке  в МГИУ  и Институте, до подписания настоящего Договора, а также с обработкой моих персональных данных любыми способами, предусмотренными федеральным законом  156-ФЗ <<О персональных данных>> и иными нормативно правовыми актами, в порядке, установленном в МГИУ и Институте согласен.}

\vskip 0.4cm
\begin{tabular}{p{8cm}p{8cm}}
Гражданин   &      Слушатель \\
\rule[-2pt]{120pt}{0.4pt}(подпись) & \rule[-2pt]{120pt}{0.4pt}(подпись)\\
\end{tabular}

\end{document}

app/views/contracts/new.html.haml
%h1 Новый контракт

= render 'form'
= link_to 'Назад', contracts_path

app/views/contracts/show.html.haml
%h1= @contract.get_contract_type? + " № #{@contract.number}"
%p
  =@contract.signing_date.strftime("%d.%m.%y")
  %br
  =@contract.start_date.strftime("%d.%m.%y")
  =@contract.finish_date.strftime("%d.%m.%y")
  %br
  =@contract.disciplines.map(&:full_name).join(', ')
  .film
    .col  
      %b Ответственное лицо:
      %br
      = @contract.fio
      %br
    .clear
 
= link_to 'PDF', contract_path(@contract, :format => :pdf)
\|
= link_to 'Редактировать', edit_contract_path(@contract)
\|
= link_to 'Назад', contracts_path
\|
- schoolkid = Schoolkid.find( @contract.schoolkid_id )
= link_to 'Школьник', schoolkid