config/routes.rb
Diplom::Application.routes.draw do
  resources :prices

  resources :users, :schools, :school_groups, :disciplines

  resources :contracts do
  end
  
  resources :groups do
    post :save_data, :on => :member
    get  :generate,  :on => :member    
  end

  resources :courses do
    post :save_data, :on => :member
    get  :generate,  :on => :member    
  end
  
  resources :schoolkids do
    get  :search,              :on => :collection
    post :change_session_year, :on => :collection
    get  :create_contract,     :on => :member
  end

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup
  match 'register' => 'users#create', :as => :register
  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  root :to => "home#index"

end

app/models/schoolkid.rb
class Schoolkid < ActiveRecord::Base
  default_scope order(:second_name, :first_name)
  paginates_per 40

  belongs_to :school_group
  belongs_to :school
  has_and_belongs_to_many :groups
  has_many :contracts, :dependent => :destroy
 
  validates :first_name,      :presence => true, :length => {:in=>2...30}
  validates :second_name,     :presence => true, :length => {:in=>2...30}
  validates :last_name,       :presence => true, :length => {:in=>2...30}
  validates :birthday,        :presence => true
  validates :addres,          :presence => true, :length => {:in=>2...300}
  validates :school_group_id, :presence => true
  validates :telephone,       :presence => true, :format => /^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$/
  
  attr_reader :school_group_tokens, :name

  def fio
    second_name + " " + first_name + " " + last_name 
  end
  
  def name
    self.fio + " " + self.school_group.number
  end

  def attributes 
    {
      'id' => id,
      'name' => name
    }
  end

  def school_group_tokens=(ids)
    self.school_group_id = ids
  end

  def self.search(fname, sname, lname)
    if (!fname.blank? or !sname.blank? or !lname.blank?) 
      where('lower(first_name) LIKE lower(?) AND lower(second_name) LIKE lower(?) AND lower(last_name) LIKE lower(?)', "%#{fname}%", "%#{sname}%", "%#{lname}%")
    end
  end
end

app/controllers/schoolkids_controller.rb
# -*- coding: utf-8 -*-
class SchoolkidsController < ApplicationController
  before_filter :check_regular_user

  def search
    @search = Schoolkid.search(params[:first_name], params[:second_name], params[:last_name])
  end
  
  def index
    respond_to do |format|
      format.html {
        @groups = Group.includes(:schoolkids).where('year = ?', session[:choice_year]).all
      }
      format.json do
        @schoolkids = Schoolkid.includes(:school_group).where("lower(second_name) LIKE lower(?) OR lower(first_name) LIKE lower(?) OR lower(school_groups.number) LIKE lower(?)", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%").all
        render :json => @schoolkids.map(&:attributes)
      end
    end
  end

  def show
    @schoolkid = Schoolkid.includes(:school_group, :contracts).find(params[:id])
  end

  def new
    @schoolkid = Schoolkid.new
  end

  def edit
    @schoolkid = Schoolkid.includes(:school_group).find(params[:id])
  end

  def create
    @schoolkid = Schoolkid.new(params[:schoolkid])
    if @schoolkid.save
      redirect_to @schoolkid, :notice => 'Школьник добавлен.'
    else
      render :action => "new"
    end
  end

  def update
    @schoolkid = Schoolkid.includes(:school_group).find(params[:id])
    if @schoolkid.update_attributes(params[:schoolkid])
      redirect_to @schoolkid, :notice => 'Школьник сохранен.'
    else
      render :action => "edit" 
    end
  end

  def destroy
    @schoolkid = Schoolkid.find(params[:id])
    @schoolkid.destroy
    redirect_to schoolkids_url, :notice=>"Школьник удален."
  end

  def change_session_year
    session[:choice_year] = params[:chosen_year].to_i
    @current_year = params[:chosen_year].to_i
    render :layout=>false
  end
  
  def create_contract
    @schoolkid = Schoolkid.find(params[:id])
    @contract = @schoolkid.contracts.build
  end 
end

app/helpers/schoolkids_helper.rb
module SchoolkidsHelper
end

app/views/schoolkids/_form.html.haml
=form_for @schoolkid,:html=>{:multipart=>true} do |f|
  -if @schoolkid.errors.any?
    .div.error
      %h2 При сохранении произошли ошибки
      %ul
        -@schoolkid.errors.full_messages.each do |msg|
          %li=msg

  .field
    = f.label :first_name
    %br
    = f.text_field :first_name
  .field
    = f.label :second_name
    %br
    = f.text_field :second_name
  .field
    = f.label :last_name
    %br
    = f.text_field :last_name
  .field
    = f.label :birthday
    %br
    =f.text_field :birthday, :size => 10
  .field
    = f.label :male
    %br
    = f.radio_button :male,"1", :checked=>@schoolkid.male?
    Мужской&nbsp;
    = f.radio_button :male,"0", :checked=>!@schoolkid.male?
    Женский
  .field
    = f.label :telephone
    %br
    = f.text_field :telephone
  .field
    = f.label :school_group_id
    %br
    =f.text_field :school_group_tokens,"data-pre"=> @schoolkid.school_group.to_a.map(&:attributes).to_json
  .actions
    = f.submit 'Сохранить'

app/views/schoolkids/change_session_year.js.haml
window.location=document.URL;

app/views/schoolkids/create_contract.html.haml
= form_for @contract do |f|
  -if @contract.errors.any?
    .msg.error
      %h2= "При сохранении произошли ошибки"
      %ul
        - @contract.errors.full_messages.each do |msg|
          %li= msg
  = f.hidden_field :schoolkid_id, :value => @schoolkid.id
  .field
    = f.label :schoolkid_id
    %br
    =f.text_field :schoolkid_tokens,"data-pre"=>Schoolkid.where(:id => @contract.schoolkid_id).map(&:attributes).to_json
  .field
    = f.label :number
    %br
    = f.text_field :number, :size => 10
  .film
    .col  
      %b Ответственное лицо:
      .field 
        = f.label :second_name
        = f.text_field :second_name, :size => 20
        &nbsp;&nbsp;
        = f.label :first_name
        = f.text_field :first_name, :size => 15
        &nbsp;&nbsp;
        = f.label :last_name
        = f.text_field :last_name, :size => 20
      .field
        = f.label :passport_number
        %br
        = f.text_field :passport_number, :size => 10
        &nbsp;&nbsp;&nbsp;&nbsp;
        = f.label :passport_series
        = f.text_field :passport_series, :size => 10
      .field
        = f.label :passport_date
        %br
        = f.text_field :passport_date, :size => 10
        &nbsp;&nbsp;&nbsp;&nbsp;
        = f.label :passport_place
        = f.text_field :passport_place, :size => 20    
      .field
        = f.label :city
        %br
        = f.text_field :city, :size => 10
        &nbsp;&nbsp;&nbsp;&nbsp;
        = f.label :address
        = f.text_field :address, :size => 20
      .field     
        = f.label :telephone
        %br
        = f.text_field :telephone, :size => 10
      .clear
  .field
    = f.label :first_sum
    =f.select(:first_sum, [0, 4980, 5000, 7500, 7600, 10000, 11400, 12500, 13000, 15000, 16500, 17500, 18200], :selected=>f.object.first_sum)
    %br
    = f.label :second_sum
    =f.select(:second_sum, [0, 4980, 5000, 7500, 7600, 10000, 11400, 12500, 13000, 15000, 16500, 17500, 18200])
  .field
    %b= f.label :ctype
    &nbsp;
    = f.radio_button :ctype, "0", :checked => @contract.ctype==0
    Основной договор
  .field
    %b= f.label :period
    &nbsp;
    = f.radio_button :period, "0", :checked => @contract.period==0
    1 год.
    &nbsp;
    = f.radio_button :period, "1", :checked => @contract.period==1
    &nbsp;
    2 года.
    = f.radio_button :period, "2", :checked => @contract.period==2
    &nbsp;
    Ускоренник
  .field
    %b= f.label :discipline_ids
    %br
    -for discipline in Discipline.find(:all)
      =check_box_tag "contract[discipline_ids][]", discipline.id, @contract.disciplines.include?(discipline)
      =discipline.full_name
      %br
  .actions
    = f.submit 'Добавить'

app/views/schoolkids/edit.html.haml
%h1 Редактированме школьника
= render 'form'
= link_to 'Показать', @schoolkid
\|
= link_to 'Назад', schoolkids_path

app/views/schoolkids/index.html.haml
%h1 Список школьников
%br
= link_to 'Добавить', new_schoolkid_path
\|
= link_to 'Поиск', search_schoolkids_path
-unless @groups.blank?
  %ul
    - @groups.each do |group|
      %li=link_to group.number, :anchor=>group.number  
  - @groups.each do |group|
    %a{:id=>group.number}=link_to group.number, group
    %table
      %thead
        %tr
          %th №
          %th ФИО
          %th
          %th
      %tbody
        - i = 1
        - group.schoolkids.each do |schoolkid|
          %tr
            %td= i
            %td=link_to schoolkid.fio, schoolkid
            %td= link_to 'Редактировать', edit_schoolkid_path(schoolkid)
            %td= link_to 'Удалить', schoolkid, :confirm => 'Вы уверены?', :method => :delete
            - i += 1
    %br

app/views/schoolkids/new.html.haml
%h1 Новый школьник
= render 'form'
= link_to 'Назад', schoolkids_path

app/views/schoolkids/search.html.haml
= form_tag search_schoolkids_path, :method => 'get' do
  =Schoolkid.human_attribute_name('second_name')
  %br
  = text_field_tag :second_name, params[:sname]
  %br
  =Schoolkid.human_attribute_name('first_name')
  %br
  = text_field_tag :first_name, params[:fname]
  %br
  =Schoolkid.human_attribute_name('last_name')
  %br
  = text_field_tag :last_name, params[:lname]
  %br
  Номер класса
  %br
  = text_field_tag :number, params[:num]
  %br
  %br
  =submit_tag "Поиск"

%br
-if !@search.blank?
  %br
  %table
    %thead
      %tr
        %th=Schoolkid.human_attribute_name('second_name')
        %th=Schoolkid.human_attribute_name('first_name')
        %th=Schoolkid.human_attribute_name('last_name')
    %tbody
      - @search.each do |schoolkid|
        %tr         
          %td=link_to schoolkid.second_name, schoolkid
          %td=link_to schoolkid.first_name, schoolkid
          %td=link_to schoolkid.last_name, schoolkid

app/views/schoolkids/show.html.haml
%p
  %b="#{Schoolkid.human_attribute_name('second_name')}:"
  = @schoolkid.second_name
  %br
  %b="#{Schoolkid.human_attribute_name('first_name')}:"
  = @schoolkid.first_name
  %br
  %b="#{Schoolkid.human_attribute_name('last_name')}:"
  = @schoolkid.last_name
  %br
  %b="#{Schoolkid.human_attribute_name('telephone')}:"
  = @schoolkid.telephone
  %br
  %b="#{Schoolkid.human_attribute_name('school_group_id')}:"
  - sg = SchoolGroup.find(@schoolkid.school_group_id)
  = link_to sg.number, sg
  %br
  %b="#{Schoolkid.human_attribute_name('school')}:"
  - s = School.find(sg.school_id)
  = link_to s.number, s
  %br  
-unless @schoolkid.contracts.blank?
  %table
    %thead
      %tr
        %th= Contract.human_attribute_name('number')
        %th= Contract.human_attribute_name('discipline_ids')
        %th= Contract.human_attribute_name('start_date')
    %tbody
      -@schoolkid.contracts.each do |contract|
        %tr
          %td= link_to contract.number, contract
          %td=contract.disciplines.map(&:full_name).join(', ')
          %td= contract.start_date.strftime("%d.%m.%Y")
%br
= link_to 'Редактировать', edit_schoolkid_path(@schoolkid)
\|
= link_to 'Добавить договор', create_contract_schoolkid_path
\|
= link_to 'Назад', schoolkids_path