config/routes.rb
Diplom::Application.routes.draw do
  resources :prices

  resources :users, :schools, :school_groups, :disciplines

  resources :contracts do
  end
  
  resources :groups do
    post :save_data, :on => :member
    get  :generate,  :on => :member    
  end

  resources :courses do
    post :save_data, :on => :member
    get  :generate,  :on => :member    
  end
  
  resources :schoolkids do
    get  :search,              :on => :collection
    post :change_session_year, :on => :collection
    get  :create_contract,     :on => :member
  end

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup
  match 'register' => 'users#create', :as => :register
  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  root :to => "home#index"

end

app/models/group.rb
# -*- coding: utf-8 -*-
class Group < ActiveRecord::Base
  default_scope order(:number)
  paginates_per 20
  
  belongs_to :course
  has_and_belongs_to_many :schoolkids

  validates :number, :presence => true, 
                     :uniqueness => true, 
                     :length => {:in=>3...30}
  
  validates :course_id, :presence => true
  validates :year,      :numericality => {:only_integer=>true, :greater_than=>1990},  
                        :presence => true

  def discipline_id
    if course_id.blank?
      discipline_id = nil
    else
      Course.find( course_id ).discipline_id
    end
  end

  def discipline_id=(val)
  end 
  
  def self.find_by_year(year)
    where('year = ?', year)
  end
    
  def group_type?
    !gtype ? "ПШ": "ФДО"
  end
  
  def groups_save(ids)
    self.schoolkid_ids = ids
  end 
end

app/controllers/groups_controller.rb
# -*- coding: utf-8 -*-
class GroupsController < ApplicationController
  before_filter :check_regular_user
  
  def save_data
    @group = Group.find(params[:id])
    @group.groups_save(params[:ids])
    render :nothing=>true
  end
  
  def generate
    @group = Group.includes(:schoolkids).find(params[:id])
    course = Course.includes(:school_groups).find(@group.course_id)
    @schoolkids = Schoolkid.where(:school_group_id => course.school_group_ids).all
    @schoolkids -= @group.schoolkids 
  end

  def index
    @groups = Group.find_by_year(session[:choice_year].to_i).page(params[:page])
  end

  def show
    @group = Group.includes(:course => [:discipline]).find(params[:id])
  end

  def new
    @group = Group.new
  end

  def edit
    @group = Group.find(params[:id])
    @school_group = SchoolGroup.where(:year => session[:choice_year].to_i)
  end

  def create
    @group = Group.new(params[:group])
    if @group.save
      redirect_to @group, :notice => 'Учебная группа добавлена.'
    else
      render :action => "new"
    end
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(params[:group])
      format.html redirect_to @group, :notice => 'Учебная группа сохранена.'
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_url, :notice => "Учебная группа удаленна"
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
=form_for @group,:html=>{:multipart=>true} do |f|
  -if @group.errors.any?
    .div.error
      %h2 При сохранении произошли ошибки
      %ul
        -@group.errors.full_messages.each do |msg|
          %li=msg

  .field
    = f.label :number
    %br
    = f.text_field :number
  .field
    = f.label :discipline_id
    %br
    .questions
      =f.collection_select :discipline_id, Discipline.all, :id, :full_name, :prompt=>"Выберете дисциплину"
  .field
    = f.label :course_id
    %br
    =f.grouped_collection_select :course_id, Discipline.order(:full_name), :courses, :full_name, :id, :start_date, :include_blank=>true
  .field
    = f.label :year
    %br
    =f.select(:year, (1990..Time.now.year).to_a.reverse, :selected=>(f.object.year || Time.now.year))
  .field
    = f.label :gtype
    %br
    = f.radio_button :gtype, "1", :checked=>@group.gtype?
    ФДО&nbsp
    = f.radio_button :gtype, "0", :checked=>!@group.gtype?
    ПШ
    %br
  .actions
    = f.submit 'Сохранить'

app/views/groups/edit.html.haml
%h1 Редактирование группы

= render 'form'

= link_to 'Показать', @group
\|
= link_to 'Назад', groups_path

app/views/groups/generate.html.haml
= link_to 'Назад', @group
\|
= link_to 'К спимку курсов', groups_path
.buttonSelect
  = button_to_function '<--', "move_value('rightTable', 'leftTable')", :class=>'button'
  %br
  %br
  = button_to_function '-->', "move_value('leftTable', 'rightTable')", :class=>'button'
  %br
  %br
  = button_to 'Сохранить',"#", :id=>'move_data'
.leftTableSelect
  %h2 Входящие в состав
  %table{:id=>'leftTable'}
    %tr
      %td
        %input{:type=>"checkbox", :onclick=>"check_all('leftTable')", :name=>"not_use"}
          Выделить все
    - @schoolkids.each do |kid|
      %tr
        %td
          %input{:type=>"checkbox", :value=>kid.id} 
            =kid.fio

.rightTableSelect
  %h2 Не входящие в состав
  %table{:id=>'rightTable'}
    %tr
      %td
        %input{:type=>"checkbox", :onclick=>"check_all('rightTable')", :name=>"not_use"}
          Выделить все
    - @group.schoolkids.each do |kid|
      %tr
        %td
          %input{:type=>"checkbox", :value=>kid.id} 
            =kid.fio

.field
  = hidden_field_tag "group_id", @group.id

app/views/groups/index.html.haml
%h1 Список учебных групп

%table
  %thead
    %tr
      %th=Group.human_attribute_name('number')
      %th=Group.human_attribute_name('year')
      %th=Group.human_attribute_name('gtype')
      -unless @groups.blank?
        %th
        %th
  %tbody
    - @groups.each do |group|
      %tr
        %td=link_to group.number, group
        %td=link_to group.year, group
        %td=link_to group.group_type?, group
        %td= link_to 'Редактировать', edit_group_path(group)
        %td= link_to 'Удалить', group, :confirm => 'Вы уверены?', :method => :delete

=paginate @groups
%br
= link_to 'Новая группа', new_group_path

app/views/groups/new.html.haml
%h1 Новая группа
= render 'form'

= link_to 'Назад', groups_path

app/views/groups/show.html.haml
%p
  %b="#{Group.human_attribute_name(:number)}: "
  =@group.number
  %br
  %b="#{Group.human_attribute_name(:discipline_id)}: "
  =link_to @group.course.discipline.full_name, @group.course.discipline 
  %br
  %b Продолжительность
  =link_to @group.course.duration, @group.course
  %br
  %b="#{Group.human_attribute_name(:year)}: "
  = @group.year
  %br
  %b="#{Group.human_attribute_name(:gtype)}: "
  = @group.group_type?

-unless @group.schoolkids.blank?
  %h2 Состав группы
  - i = 1
  %table
    %thead
      %tr
        %th №
        %th ФИО
    %tbody
      - @group.schoolkids.each do |kid|
        %tr
          %td= i
          %td= link_to kid.fio, kid
        - i += 1

%br
= link_to 'Редактировать', edit_group_path(@group)
\|
=link_to 'Назад', groups_path
\|
= link_to 'Сформировать состав', generate_group_path(@group)